import psycopg2
from openpyxl import load_workbook
from time import sleep


def create_table_postg_db(*args):
    connection = psycopg2.connect(database=args[0], user=args[1], password=args[2], host=args[3], port=args[4])
    sql = 'CREATE TABLE contratos ' \
          '(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,' \
          'icj TEXT NOT NULL,' \
          'equipamento TEXT, ' \
          'embarcacao TEXT NOT NULL,' \
          'chave_gerente TEXT,' \
          'gerente TEXT,' \
          'chave_fiscal TEXT,' \
          'fiscal TEXT,' \
          'empresa TEXT NOT NULL,' \
          'inicio DATE,' \
          'termino DATE, ' \
          'cessão TEXT);'

    cur = connection.cursor()
    cur.execute(sql)
    connection.commit()
    connection.close()
    print("Opened database successfully")
    return 'Tabela criada com sucesso'


def delete_table(*args):
    connection = psycopg2.connect(database=args[0], user=args[1], password=args[2], host=args[3], port=args[4])
    sql = 'DROP TABLE contratos;'
    cur = connection.cursor()
    cur.execute(sql)
    connection.commit()
    print('Planilha deletada com sucesso!!!')
    connection.close()


def insert_data_table(*args):
    dict_gerais = args[6]
    connection = psycopg2.connect(database=args[0], user=args[1], password=args[2], host=args[3], port=args[4])
    for contrato_icj in args[5]:
        extracao = dict_gerais[contrato_icj]
        sql = 'INSERT INTO contratos (icj, equipamento, embarcacao, chave_gerente, gerente, chave_fiscal, fiscal, ' \
              'empresa, inicio, termino, cessão) ' \
              'VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'
        values = (contrato_icj, extracao[0], extracao[1], extracao[2],
                  extracao[3], extracao[4], extracao[5], extracao[6], extracao[7], extracao[8], extracao[9])
        cur = connection.cursor()
        cur.execute(sql, values)
        connection.commit()
        print(cur.rowcount, f'Registro da embarcação {extracao[1]} foi inserido com sucesso!!!')
    connection.close()


def catalogar(*args):
    dict_dados = {}
    lista_dados = []
    lista_icj = []
    contador = args[0].max_row
    for linha in range(2, contador + 1):
        icj = args[0].cell(row=linha, column=1).value
        lista_icj.append(icj)
        lista_indice = [2, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        for coluna in lista_indice:
            info = args[0].cell(row=linha, column=coluna).value
            lista_dados.append(info)
        dict_dados[icj] = lista_dados
        dict_dados.copy()
        lista_dados = []
    return lista_icj, dict_dados


def consult_ger(*args):
    connection = psycopg2.connect(database=args[0], user=args[1], password=args[2], host=args[3], port=args[4])
    sql = f'SELECT * ' \
          f'FROM contratos ' \
          f'WHERE icj = %s;'
    values = (args[5],)
    cur = connection.cursor()
    cur.execute(sql, values)
    rows = cur.fetchall()
    return rows

def update_fiscal(*args):
    connection = psycopg2.connect(database=args[0], user=args[1], password=args[2], host=args[3], port=args[4])
    sql = 'UPDATE contratos ' \
          'SET chave_fiscal =%s ,fiscal = %s ' \
          'WHERE icj = %s;'
    values = args[5]
    cur = connection.cursor()
    cur.execute(sql, values)
    connection.commit()
    updated_rows = cur.rowcount
    cur.close()
    consult = consult_ger(args[0], args[1], args[2], args[3], args[4], args[5][2])
    return f'Foi alterado {updated_rows} registros com sucesso!!!\n{consult}'



def main():
    wb = load_workbook(filename='Planilha Guia_dados.xlsx')
    sheet = wb['Info Contrato']
    dados_contratual = catalogar(sheet)
    nova_lista = sorted(set(dados_contratual[0]))
    insert_data_table("testdb", "root", "1234", "127.19.0.2", "5432", nova_lista, dados_contratual[1])
    wb.close()


# delete_table("testdb", "root", "1234", "127.19.0.2", "5432")
# sleep(2)
# result = create_table_postg_db("testdb", "root", "1234", "127.19.0.2", "5432")
# print(result)
# sleep(2)
# main()
icj_ship = str(input('Digite o ICJ do barco:'))
barco = consult_ger("testdb", "root", "1234", "127.19.0.2", "5432", icj_ship)
print(barco)
# fiscal_updated = update_fiscal("testdb", "root", "1234", "127.19.0.2", "5432", ('EF8W', 'Maria Lusinete', icj_ship))
# print(fiscal_updated)
